### ISSUE TITLE
Agentname CLI parameter has no effect on the actual agent name shown in the manager

### ISSUE THREAD

**Issue by vaistomarkus** [damies13/rfswarm#100]
**Description**
The -a or --agentname option for rfswarm-agent is not updating the actual agent name shown in the rfswarm-manager.

**To Reproduce**
1. Start rfswarm-agent with -a or --agentname option
`rfswarm-agent -a use-this-name` or `rfswarm-agent --agentname use-this-name`
2. Start rfswarm-manager and go to "Agents" page
3. See that the agent name does not equal the given name `use-this-name`

**Expected behavior**
The CLI parameter should be used for the test but it should not override the value in the .ini file. Also if the .ini file does not contain `agentname`, it should be set to equal the machine hostname.

**Comment by damies13** [comment]
Thank You Markus for this bugfix.

Fix has been merged into release 0.9.0 branch
