### ISSUE TITLE
Clarifications in total elapsed time of test run 

### ISSUE THREAD

**Issue by chidambaranathan-r** [damies13/rfswarm#112]
rfswarm version: 1.0.0
Both manager and agent are running in the same node (docker container).
Run mode: non-gui

We used the below configuration:

```
test.rfs
[Scenario]
scriptcount = 1

[1]
users = 10
delay = 0
rampup = 10
run = 30
test = sample performance test using rfswarm
script = /opt/robotframework/tests/pqm_characteristics/performance_efficiency/capacity.robot
```

The expectation here is, the 10 robot users will be ramped up in 10 seconds and the robots will run the test for 30 seconds. So, the overall test time should be ~40 seconds. But in the log it looks like ~4 minutes. (Test Started:    1646824481 [ 2022-03-09 11:14:41 ], Test Completed:  1646824628 [ 2022-03-09 11:18:18 ])

```
rfswarm -g 2 -n -r -s test.rfs

Robot Framework Swarm: Manager
        Version 1.0.0
        Configuration File:  /usr/local/lib/python3.8/dist-packages/rfswarm_manager/RFSwarmManager.ini
Starting Agent Manager http://d84f5cb164c1:8138/
datapath: /usr/local/lib/python3.8/dist-packages/rfswarm_manager/results/PreRun
Waiting for Agents
Manager Connected http://localhost:8138/ 2022-03-09 11:14:30 ( 1646824470 )
Waiting for Agents
Test Started:    1646824481 [ 2022-03-09 11:14:41 ]
datapath: /usr/local/lib/python3.8/dist-packages/rfswarm_manager/results/20220309_111441_test
Robot: 1        Test: sample performance test using rfswarm     Assigned to: d84f5cb164c1
Robot: 2        Test: sample performance test using rfswarm     Assigned to: d84f5cb164c1
Robot: 3        Test: sample performance test using rfswarm     Assigned to: d84f5cb164c1
Robot: 4        Test: sample performance test using rfswarm     Assigned to: d84f5cb164c1
Robot: 5        Test: sample performance test using rfswarm     Assigned to: d84f5cb164c1
Robot: 6        Test: sample performance test using rfswarm     Assigned to: d84f5cb164c1
Robot: 7        Test: sample performance test using rfswarm     Assigned to: d84f5cb164c1
Robot: 8        Test: sample performance test using rfswarm     Assigned to: d84f5cb164c1
Robot: 9        Test: sample performance test using rfswarm     Assigned to: d84f5cb164c1
Robot: 10       Test: sample performance test using rfswarm     Assigned to: d84f5cb164c1
Robot Ramp Up Completed

Test Completed:  1646824628 [ 2022-03-09 11:18:18 ]
Summary File: /usr/local/lib/python3.8/dist-packages/rfswarm_manager/results/20220309_111441_test/20220309_111441_test_summary.csv
Agent Data: /usr/local/lib/python3.8/dist-packages/rfswarm_manager/results/20220309_111441_test/20220309_111441_test_agent_data.csv
Raw Result Data: /usr/local/lib/python3.8/dist-packages/rfswarm_manager/results/20220309_111441_test/20220309_111441_test_raw_result_data.csv
Shutdown Agent Manager
Exit

```

What could be reason for this?

Any pointers would be helpful?

**Comment by damies13** [comment]
Hi @chidambaranathan-r ,

Thanks for the question, hopefully this clarifies things, I guess I need to update the documentation to make this clearer, could you suggest where in the documentation you would have looked for this information?

Your scenario is configured for 10 robot users will be ramped up in 10 seconds and the robots will run the test for a minimum of 30 seconds. So, the overall test time should be at least 40 seconds.

You'll notice a slight difference in my wording above.

You will probably want to have a read of [agent polling of the manager](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_agent.md#agent-polling-of-the-manager) from the documentation.

1. Regarding ramp up, the agents get assigned robots (on the manager) in this ramp up time, there will be a small delay from when the robot is assigned to the agent to when the robot actually starts running (this is similar to other performance test tools), 

- The agent initially is only polling ever 10 sec, so it can be up to 10 sec before the agent knows it has a robot assigned to run, but once it does it will then poll every 2 sec to find out about the additional robots it needs to run.
- Once the agent knows it needs to run a robot it will start the robot immodestly if the current time is after the start time, but depending on the library you use and the agent hardware it could take a few seconds to start up, for example if you are using selenium library it could take 2-15 seconds just to open the browser before you actually start loading the web page

2. Regarding the run time, the 30 seconds is the minimum run time, this run time determines how long the robot test cases keep getting restarted for, after the run time is finished, the test will enter the ramp down stage where the robots that are running will continue running until they finish but they will not be restarted.

- Assume you set your ramp up to 20 sec and all 10 robots have started within the 20 sec ramp up period and your run is configured for 30 sec
    - if each robot takes 20 sec to run it's test case, then by 5 sec into the run phase it might be finished it's first iteration, so robot 1 will start again at ~25 sec, and run a further 20 sec, then at  ~45 seconds robot 1 finished its second iteration (20+30=50) we 5 seconds before the end of the run phase so robot 1 starts it's 3rd iteration and runs until ~65 seconds from start. In this scenario a coupe of robots will run 3 iterations and most will run 2 iterations of the robot test case.
    - if each robot takes 3:50 sec to run it's test case, then all robots will run 1 iteration each as buy the time the first robot has finished it's first iteration it will be ~3 minutes after the ramp down phase started and in total the test will take about 4:10 - 4:20   

I guess your test is more like this second example?

**Comment by damies13** [comment]
I guess by no comment since March this is answered, will close for now.
