### ISSUE TITLE
Unable to open rfswarm.py (GUI / Server)

### ISSUE THREAD

**Issue by ZA-gRAPHic** [damies13/rfswarm#12]
Receive the error below after running python rfswarm.py:

C:\Users\raphaelr\Desktop\rfswarm-master>python rfswarm.py
Traceback (most recent call last):
  File "rfswarm.py", line 2690, in <module>
    rfs = RFSwarmGUI()
  File "rfswarm.py", line 355, in __init__
    self.BuildUI()
  File "rfswarm.py", line 430, in BuildUI
    self.BuildPlan(p)
  File "rfswarm.py", line 577, in BuildPlan
    self.pln_graph.pack(fill="both", expand=True)
  File "C:\Python37\lib\tkinter\__init__.py", line 2143, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside .!rfswarmgui.!notebook.!frame which already has slaves managed by grid

Running Python 3.7 on Windows 10, have configparser==4.0.2, requests==2.22.0 and psutil==5.6.5 installed.

**Comment by damies13** [comment]
Firstly, Thanks for trying rfswarm out.

This is an interesting error, hopefully we can figure it out.

I was initially going to ask if you had tkinter installed, but from reading through the stack trace it's obvious you do, so I guess we need to find out which version?

from a python3.7 prompt can you run the following commands to check your tkinter version:

```
>>> import tkinter
>>> tkinter.TkVersion
```

For reference this is what I get:

```
DavesMBP:rfswarm dave$ python3
Python 3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> tkinter.TkVersion
8.5
>>> 
```

In the meantime I'll start checking if there is any known issues around this between between 8.5 and 8.6.

**Comment by damies13** [comment]
I think I found the problem
This line:
`		self.pln_graph.pack(fill="both", expand=True)`
Is not actually needed, as the line below does the same thing and they are conflicting:
`		self.pln_graph.grid(column=0, row=planrow, sticky="nsew")`

It didn't error for me, so I missed that, it looks like the tkinter on your machine is being more fussy, so I would still like to know which version you have.

In the meantime, can you just comment out or remove line 577 in "rfswarm.py" and see if that gets you working?

I have checked the code and it seems this is the only place I used .pack, so this should be the only line you need to change, I will also push a bugfix for this.

**Comment by ZA-gRAPHic** [comment]
Thanks for the feedback, made the suggested change and able to launch the RF Swarm GUI.
