### ISSUE TITLE
Reporter: Option to filter by Agent

### ISSUE THREAD

**Issue by pkievit86** [damies13/rfswarm#121]
For localization testing we need to be able to distinguish measurements for each agent. Network latency for an office where personnel are complaining can be measured and viewed this way.

For all charts, tables, it would be great if this could be filtered. Possibly even through a CLI parameter so you can generate individual reports.

**Comment by damies13** [comment]
The data to do this is mostly already in the database


- [x] Results data - agent column in results table
- [x] Agent metrics (cpu, memory etc for the agents) - Primary Metric in MetricData View
- [ ] other metrics

My initial thoughts on how to implement this: 
- [] add a agent column to the Metric table so all metrics can have this option.
- [] add an agent drop down to the filters (might need to grey this out if opening a database where metric table doesn't have the agent column)

**Comment by damies13** [comment]
This was a lot more work than I expected, but I think it turned out well, also implemented Feature Request #105 at the same time as I was modifying all the tame places I would have needed to do for that feature and it was easier to do them together.

This is now merged into the v1.1.0 release branch.

**Comment by pkievit86** [comment]
Great work! I will give it a try as soon as I can.

**Comment by damies13** [comment]
> Great work! I will give it a try as soon as I can.

I'm aiming to release V1.1.0 on Friday, but your welcome to download the 1.1.0 branch if you want to try it out before then, if you do let me know if you find any issues.
