### ISSUE TITLE
Manager: Add keyboard shortcuts to Example Graphs

### ISSUE THREAD

**Issue by pkievit-copado** [damies13/rfswarm#122]
From within a VNC session where no input is possible, I would like to programmatically view the Graph while running a test. Can we add keyboard shortcuts to it as you have now for creating a new graph.

Relates to:
Graphs
New with version 0.8.0 is the ability to have live graphs during the test run displaying various data about the test.

**Comment by damies13** [comment]
Hi,

I have been thinking about this for a bit trying to understand the request.

let me start with a screen shot of the Graphs menu, I know this is the Mac version but the menu is basically the same.

<img width="353" alt="Screenshot 2023-02-05 at 8 05 38 pm" src="https://user-images.githubusercontent.com/15232871/216812867-daa34478-13dd-42a2-8528-ac71039ae745.png">

As you mentioned there is already shortcut key (Control/Command + G) for a new graph.

Are you asking for shortcut keys for the graphs on the Examples sub menu? How about the Recent sub menu and Scenario sub menu?

I'm thinking maybe I could use Control/Command + 0-9 for the first 10 graphs on the scenario sub menu, Control/Command + Shift+ 0-9 for first 10 graphs on the recent sub menu. 

You probably need to know apart from the the Examples sub menu the other sub menus are dynamic based on which graphs you previously opened.

The other thing I'm curious about is why you need to open the graphs programatically? When you open an existing scenario the graphs that were open last time you saved the scenario should be reopened.

Dave.

**Comment by pkievit86** [comment]
@damies13 thank you for your reply. I want to display different graphs based on keyboard inputs so yes you are correct. But if you mentioned last openend graphs are saved I do see this as an option. Question I have here is, are those previously opened graphs stored in the .rfs file or some place else?

**Comment by damies13** [comment]
Yes they are stored in the .rfs file, here's an example .rfs file that has 3 graphs if you're interested in the detail:

```
[Scenario]
scriptcount = 2
graphlist = 60b9c0df-e,60bed82d-a,60bed84a-b

[1]
robots = 10
delay = 0
rampup = 300
run = 1200
test = Browse Store 10
script = ../robots/OC_Demo_2.robot

[2]
robots = 10
delay = 420
rampup = 300
run = 1800
test = Browse Store 10
script = ../robots/OC_Demo_2.robot

[60b9c0df-e]
id = 60b9c0df-e
open = True
win_width = 474
win_height = 253
win_location_x = 498
win_location_y = 619
win_screen = :0.0
name = Agent Robots
show_settings = False
show_legend = 1
data_type = Metric
metric_type = Agent
primary_metric = 
secondary_metric = Robots

[60bed82d-a]
id = 60bed82d-a
open = True
win_width = 460
win_height = 251
win_location_x = 37
win_location_y = 619
win_screen = :0.0
name = Running Robots
show_settings = False
show_legend = 0
data_type = Metric
metric_type = Scenario
primary_metric = 
secondary_metric = total_robots

[60bed84a-b]
id = 60bed84a-b
open = True
win_width = 460
win_height = 253
win_location_x = 973
win_location_y = 619
win_screen = :0.0
name = Agent Load
show_settings = False
show_legend = 1
data_type = Metric
metric_type = Agent
primary_metric = 
secondary_metric = Load

```

**Comment by pkievit86** [comment]
Thank you for sharing. I will use this. Up to you if you want to close this one.

**Comment by damies13** [comment]
I will probably close this as I'm not sure that the shortcut keys are that useful, but not that difficult to implement the way I mentioned either.

Are you generating the scenario as part of a CICD? if so and you want to know how to enable a setting simply perform the action in gui and save the scenario. All the configuration is in this .rfs file, I deliberately kept it a simple ini file style text file so that people could generate one dynamically if needed. Within rfswarm the .rfs file is read/written using the [configparser](https://docs.python.org/3.8/library/configparser.html) python module, so if you can use the same module to dynamically generate a scenario if you want.

**Comment by pkievit86** [comment]
Not yet, saving it manually for now. If needed I will look into it. Thank you.

**Comment by damies13** [comment]
I'll close this for now, it can be reopened if someone thinks shortcut keys for the graphs on the Examples sub menu would be really useful.
