### ISSUE TITLE
Executed tests - nothing seems to be happening

### ISSUE THREAD

**Issue by ryanrosello-og** [damies13/rfswarm#124]
Hi 
I have this basic test:
```
*** Settings ***
Library   Browser

*** Test Cases ***
Example Test
    New Page    https://playwright.dev
    Get Text    h1    ==    Playwright enables reliable end-to-end testing for modern web apps.
```

Which I added to a simple test plan:
![Screenshot_20230205_072505](https://user-images.githubusercontent.com/50574915/216811470-24dcb72e-c0b8-4d51-be5f-fd89b738f295.png)

After a few minutes, I was expecting the test to complete and show some details on the Run tab?
![Screenshot_20230205_072530](https://user-images.githubusercontent.com/50574915/216811497-813b3551-5377-43d5-892d-df07498efd9e.png)

But nothing seemed to have happened, the Manager shows "Test Started ..."
![Screenshot_20230205_072612](https://user-images.githubusercontent.com/50574915/216811562-82ebbf86-b4bd-4544-a43b-937c0c52ef17.png)

And the agent seems to be connected fine:

![Screenshot_20230205_072555](https://user-images.githubusercontent.com/50574915/216811542-1b06f7ff-8e47-4bda-bc5e-3558cd40013d.png)

I then clicked one of these buttons and the manager becomes unresponsive:

![Screenshot_20230205_073321](https://user-images.githubusercontent.com/50574915/216811672-9a1e39de-93ba-4f4f-862d-18e8e5f3ea9e.png)

**NOTES**:  I'm running windows 11, Python 3.11.1, pip 22.3.1
both the agent and manager are running on the same machine.

**Comment by damies13** [comment]
Hi Ryan,

It looks like you didn't select which test you want to execute
![216811470-24dcb72e-c0b8-4d51-be5f-fd89b738f295](https://user-images.githubusercontent.com/15232871/216812221-1e51b50f-1a05-420d-be87-a8664900bebc.png)

Dave.

**Comment by ryanrosello-og** [comment]
thanks, yup I did not select a test
