### ISSUE TITLE
Is there a way to exclude think times from the reports?

### ISSUE THREAD

**Issue by ryanrosello-og** [damies13/rfswarm#125]
Is there a way to exclude think times from the reports?

**Comment by damies13** [comment]
Yes you can use the filters see: [Data Graph Result](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_reporter.md#data-graph-result)

But the think time can't be excluded from the measured keyword (transaction) time as that's recoded by robot framework itself (rfswarm has no control over that), so I recommend not putting think time in keywords where measuring the time of the keyword is important to you.

Dave.

**Comment by ryanrosello-og** [comment]
👍 thanks for the info
