### ISSUE TITLE
How to view test results summary

### ISSUE THREAD

**Issue by ryanrosello-og** [damies13/rfswarm#127]
Hi, I'm a bit lost, after completing a simple load test.  How do I view a quick summary of the results?

Would I need to manually create a report via the reporter ? If so, do you happen to have a template for this or would I need to create it manually first?

**Comment by damies13** [comment]
Hi Ryan,

1) The easiest way is to click the [CSV Report button](https://github.com/damies13/rfswarm/blob/v1.1.0/Doc/rfswarm_manager.md#csv-report-button-) ![image](https://user-images.githubusercontent.com/15232871/218617270-36130e41-1a6e-456c-8378-a6767d3360b7.png) button on the run screen, this will give you a csv file you can open in excel or what even you want, but only gives you the information from the run screen.

2) You can use reporter, it will open with a very basic template as a starting point and you can modify the templates to suite your needs

3) The results from rfswarm are actually stored in an sqlite file so you can use any tool you like that has sqlite libraries to query the result database directly, e.g. [python sqlite3 module (this is what rfswarm uses)](https://docs.python.org/3/library/sqlite3.html), [DB Browser for SQLite](https://sqlitebrowser.org/), etc

Dave.

**Comment by ryanrosello-og** [comment]
thanks, yeah this was possibly obscured by https://github.com/damies13/rfswarm/issues/128

**Comment by damies13** [comment]
This issue should be resolved by the fix for #128 and Release v1.0.1
