### ISSUE TITLE
Problem with test case name

### ISSUE THREAD

**Issue by sailindaze** [damies13/rfswarm#13]
To get things to work on Windows 10 with Python 3.7.5 I had to change line 441 in rfswarm_agent.py from cmd.append("'"+test+"'") to cmd.append('"'+test+'"').  Single quotes around the test case name in the Robot command line weren't working - they need to be double quotes for Windows.

**Comment by damies13** [comment]
Hi John,

Good catch, I suspected that quotes would be needed for paths with spaces, and i'd forgotten that Windows only accepts double quotes (been a while since I used Windows regularly).

Thanks for this bug report and for trying out rfswarm.

**Comment by damies13** [comment]
I believe this is resolved.
