### ISSUE TITLE
Is there an easy to troubleshoot why an agent would fail to Stop?

### ISSUE THREAD

**Issue by ryanrosello-og** [damies13/rfswarm#130]
Is there an easy to troubleshoot why an agent would fail to Stop?

In my simple example below, I ran a basic test for 45 seconds but then the total elapsed time blew out to about 7 minutes and still not yet finish.  These test runs within 30 seconds normally using Robot.

* I did look at the output directories but unfortunately there is nothing useful in there yet possibly because the agent is hung?

![2023-02-15_11-02-07](https://user-images.githubusercontent.com/50574915/218904767-600743b9-4e53-4bd5-a264-fea1c9d122b2.jpg)

**Comment by damies13** [comment]
Hi Ryan,

When the Manager is in stopping mode (either after pressing stop or after the end of the run time as is the case here) the agents will allow the robot to continue running the test that is currently running until it's completion but won't start a new one after the robot completes its current test.

You mentioned these tests normally run for ~30 sec

Your ramp up is only 10 sec which is a bit short (the agents only poll every 10 sec when in the ready state, so the ramp-up may have taken a bit longer but as you only had 2 robots and 1 agent not likely more than 15 sec.

worst case this test should have not run more than 90 seconds and should definitely been done by 2 min. so running for 7 minutes indicates they test are taking longer for some reason.

While running there's no real way to diagnose, though I see only 1 robot is running so it indicates it got stuck somehow? you could just wait till it times out (robot framework has timeouts so the test shouldn't run forever) and then look at the robot logs to see why?

Alternatively if you don't want to wait you can abort the test, on the run screen you'll see the stop button changed to a bomb button, pressing this will tell the agents to send a sighup to any running robots (like sending a Control+C to the robot command window) and then you can look to the robot logs when the agent sends them back to the manager.

**Comment by damies13** [comment]
I guess by no comment since Feburary this is answered, will close for now.
