### ISSUE TITLE
Running with Command Line Interface : It's not working

### ISSUE THREAD

**Issue by P-U-M-K-I-N** [damies13/rfswarm#131]
**Describe the bug**
I run rfswarm and rfswarm-agent with Command Line Interface and it's not working. But I run with GUI , it's work.

**To Reproduce**
1. Open 2 cmd windows 
2. rfswarm's side run by : rfswarm -s C:/Users/admin/Desktop/report_robot_test/resultTest/swarm_test.rfs -r
3. rfswarm-agent's side run by : rfswarm-agent -m http://localhost:8138/ -r 2 -x -a testRFtest
4. rfswarm-agent's side show log as Manager Connected http://localhost:8138/ 2023-02-23 11:33:40 ( 1677126820 )
5. rfswarm show log as Test Started:    1677126830 [ 2023-02-23 11:33:50 ]
6. I waited a long time but no other logs are shown 

**Expected behavior**
Agent having assigned but robots is not working. How can I fix it?

**Screenshots**
![image](https://user-images.githubusercontent.com/124129264/220823760-0e86e887-8c6c-46d0-a351-2d8c8f51bce5.png)
![image](https://user-images.githubusercontent.com/124129264/220823796-4b5f09d8-e33f-4eff-a90f-2dfeefd32ea0.png)
![image](https://user-images.githubusercontent.com/124129264/220823827-1d1dbcf7-2873-4da8-a458-388acd1da77f.png)
![image](https://user-images.githubusercontent.com/124129264/220823855-b7bed917-5bbf-4326-9434-78811eaba66e.png)
![image](https://user-images.githubusercontent.com/124129264/220824393-b5687d1c-845b-48a3-b51f-4240acd68527.png)

**Desktop (please complete the following information):**
 - OS: window
 - Browser : chrome
 - Version : 1.0.0

**Additional context**

**Comment by damies13** [comment]
Hi @P-U-M-K-I-N 

Did you have the GUI manager open when you run the command line manager (running 2 managers at once)? I'm not sure what would happen if you did this, I expect the agent will connect to the first manager that was running (the GUI)

Guessing you didn't have the GUI manager open, when running the command line manager it's a good idea to have the agents already running (they'll just sit in a disconnected state), but this shouldn't be the issue either because by default the Manager should wait until there's an agent connected before starting the test and it says your test started.

By default the manager doesn't put much else out to the command window until the test is finished, however if you use the -g option you'll get increased messaging, debug levels 0-3 should be fine for normal running of scenarios each giving more info, debug levels > 4 are really only for debugging when testing code updates, 9 is pretty noisy so i don't recommend it.

If I remember correctly debug level 1 should give you information about agents connecting and 2 tells you every time a robot is assigned to an agent.

You can also use the increased debug level on the agent as well to see when robots are started and other activity received from the manager.

Being fairly quiet by default is by design, you don't want your CI logs being filled up unnecessarily, it should only send the most  important messages by default.

Hopefully is not a bug,

Dave.

**Comment by P-U-M-K-I-N** [comment]
I add -g 3 in Agent and Manager command then they show this...
![image](https://user-images.githubusercontent.com/124129264/223369068-509e4daa-e5ba-4e82-ba16-2b47a40949c6.png)
![image](https://user-images.githubusercontent.com/124129264/223369045-2b7f30c0-883e-48a7-8ff8-71b89b3d8036.png)

This is my Robot framework code...
![image](https://user-images.githubusercontent.com/124129264/223369693-67edf3bd-a854-49ad-b87c-615c41a57a14.png)

**Comment by damies13** [comment]
Hi @P-U-M-K-I-N 

Well that confirms that it's working, the test is running and assigning robots to the agent, the agent is attempting to run those robots. 

There are 2 problems I see:

1. Your agent machine doesn't have robot framework installed or the agent can't find robot framework executable

![Screenshot from 2023-03-07 21-47-21](https://user-images.githubusercontent.com/15232871/223414925-2eae46ee-c5df-46d5-b01b-d743cd646d53.png)

You need to have Robot framework and any libraries you need installed in the same environment as rfswarm-agent. Another problem that happens on Windows is path related issues, I noticed in recent testing on windows that when python is installed for the current user the python directories are added incorrectly to the path so you might be encountering that issue too.

Have a look at this article [What if you forget to add Python to the PATH variable?](https://www.pylenin.com/blogs/why-add-python-to-path/), just note the last screen shot is wrong the last `\` at the ends of the first 2 paths shouldn't be there, it causes robot and other python applications to not be found in the path.

If you have robot framework installed but are still having this issue then you can tell the agent where the robot executable file is by adjusting the [Robot Command](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_agent.md#robot-command) setting in the ini file.

2. You don't have any keywords that will return a result. 

Start by having a look at [Keywords](https://github.com/damies13/rfswarm/blob/master/Doc/Preparing_for_perf.md#Keywords) from [Preparing a test case for performance](https://github.com/damies13/rfswarm/blob/master/Doc/Preparing_for_perf.md#preparing-a-test-case-for-performance) in the documentation.

`Evaluate`, `Sleep` and `Log To Console` are all from the default [excluded libraries](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_agent.md#exclude-libraries) list, and `Go to webpage` and `random sleep` are the same as the `Quiet Keyword` example in [Keywords](https://github.com/damies13/rfswarm/blob/master/Doc/Preparing_for_perf.md#Keywords).

I actually recommend reading all of  [Preparing a test case for performance](https://github.com/damies13/rfswarm/blob/master/Doc/Preparing_for_perf.md#preparing-a-test-case-for-performance) at least once as it has lots of useful tips.

This may seem like a bit of extra work to get going, but the control it gives you is worth it when it comes time to report your results.

Dave.

**Comment by damies13** [comment]
Hi @P-U-M-K-I-N ,

Something else I just noticed `-r 2 -x` in the title bar of that window.

The number 2 is not a robot executable. this -r option is for passing the path to `robot.exe` if you are having issues with the path.

As for `-x` this is a backwards compatibility option if you are running very old versions of robot framework (before robot framework v4). While is should still work, this mode is very slow, the test has to finish running and create the output.xml file, after the robot exits the agent will then parse the xml for the transactions. The listener method is much faster as it triggers sending the response time as soon as the keyword ends.So this option should only be used as a last resort.

Dave.

**Comment by P-U-M-K-I-N** [comment]
It's work. I set `PATH variable in Environment` and remove `-r 2 -x` from command.
![image](https://user-images.githubusercontent.com/124129264/223619806-b3df2c56-895a-4650-9315-d15734021127.png)
![image](https://user-images.githubusercontent.com/124129264/223619775-474ab75e-29ed-42f8-98a2-85a14a4379c8.png)

 Thank you.

**Comment by P-U-M-K-I-N** [comment]
May I ask more?
I wonder about `-t STARTTIME, --starttime STARTTIME` that mean time to start? or total running time?

**Comment by damies13** [comment]
Hmmm I thought the help text with that option made it obvious:
> Specify the time to start the test HH:MM or HH:MM:SS (ISO 8601)

Maybe I should include the word scheduled?

It's the same as the [Schedule start time](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_manager.md#schedule-start-time-) in the Manager GUI

It's an option you might use if you want your test to start at a specific time, for example, you've lined up several support teams and they've all agreed to start monitoring from 17:45 and you'll start the test at 18:00. 

When you're preparing for the test you set the start time as 18:00 (or maybe even 18:00:03 if your superstitious and want to start a few seconds after the hour)
Then run the manager the agents will connect and they'll all just sit there ready to go and as soon as the start time ticks around the ramp-up will start.

There's also a similar feature in Loadrunner, some teams I've worked with they use it all the time, other teams never use it, but it's up to you if it's useful, if not ignore it.

**Comment by P-U-M-K-I-N** [comment]
Thank you Dave.
