### ISSUE TITLE
DLL load failed while importing _cert

### ISSUE THREAD

**Issue by ish91** [damies13/rfswarm#142]
Freshly installed rfswarm-manager package gives the following error when I try to run 'rfswarm' in a python virtual environment:
**DLL load failed while importing _cert: The specified module could not be found.**

Python version: 3.9.13
The python venv does not contain any other packages. What do I miss?
Thanks!

**Comment by damies13** [comment]
Hi @ish91 

In the [Manual Install the prerequisites](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_manager.md#4-manual-install-the-prerequisites) section of the documentation I covers what's required, I've not used virtual environment myself, though I know others do, so I know it should work.

Did the error tell you what DLL it failed to load?

Beyond that, I run rfswarm on a completely clean version of windows with python 3.9 as part of the development process here's is the requirements.txt file the build server uses:

```
robotframework
robotframework-SikuliLibrary
robotframework-imagehorizonlibrary
opencv-python
configparser
requests
HTTPServer
pillow
psutil
pip>=21
matplotlib>=3.5.1
``` 

These 4 are needed by the test cases not rfswarm:
```
robotframework
robotframework-SikuliLibrary
robotframework-imagehorizonlibrary
opencv-python
```
So perhaps you might need requests? I see that's missing from the documentation so it could be that.

Did you install using `pip* install rfswarm-manager` or did you clone the project and run the rfswarm.py file? this might help to work out the issue.

FYI here is the [test log](https://github.com/damies13/rfswarm/actions/runs/4571317938/jobs/8069502296) of the release version of rfswarm on win windows with python 3.9, looks like is was tested with the same version Python 3.9.13. but not in a python virtual environment. 
(I know the tests are a bit light on at the moment, I plan to improve that over the next few releases, this was just a starting point to ensure rfswarm at least runs on each platform and each python version)

Dave.

**Comment by ish91** [comment]
yeah well I found the issue.
matplotlib install was unsuccessful because this package depends on vs_BuildTools (which was missing on the host)
This quick install fixed the problem and now rfswarm command does open what it should.
thanks anyway!

**Comment by damies13** [comment]
Hi @ish91 ,

Glad you found the issue, and relieved to hear it wasn't a bug with rfswarm.

Dave.
