### ISSUE TITLE
Execption error thrown continuously in rfswarm-manager terminal

### ISSUE THREAD

**Issue by DineshSridhar** [damies13/rfswarm#153]
I have installed RFSwram in macOS.Started the rfswarm agent and rfswarm manager as well.Once launching rfswarm application got opened and I heed added robot testcases.After uploading file in rfswarm terminal its started to throw error continuously  

Exception in thread Thread-17325 (find_dependancies):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-17290 (find_dependancies):
Traceback (most recent call last):
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
Exception in thread Thread-9621 (find_dependancies):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
Exception in thread Thread-17408 (find_dependancies):
Traceback (most recent call last):
Exception in thread Thread-9630 (find_dependancies):
    self._target(*self._args, **self._kwargs)

**Comment by damies13** [comment]
Hi Dinesh,

Can you advise 
- which version of MacOS are you running?
- Did you install python 3.10, or is it the default python version? If you installed, how?
- Is this error being thrown by the agent or the manager?

I'll try to find a way to reproduce this if I can.

Dave.

**Comment by damies13** [comment]
Hi Dinesh,

Unfortunately I don't have an M1 Mac to try things on, from what I was able to find Python 3.9.x + should work on M1 Macs.

Are you running 3.10.0, 3.10.12 (latest), or a version in between.

The exception is being thrown in threading.py which is core python code and I can't see any reason for it, "find_dependancies" is a function in the manager, there are 2 places in that function where it can start a new thread, but from what I can tell it's not the rfswarm code that's causing the exception.

- If your not running 3.10.12, try updating to 3.10.12 and see if that resolves the issue (hopefully whatever you've stumbled across has been fixed :crossed_fingers: )
- If your are running 3.10.12, try downgrading to an earlier version of python 3.10 and hopefully this is an issue that was introduced buy a recent release.

Unfortunately, my Mac is an old i7 Macbook and it has python 3.9, I know this configuration works.

I did setup the github actions to run rfswarm on all python versions but unfortunately the tkinter component was the wrong version on the github actions macs for python 3.10 so I wasn't able to run any test on that python version for MacOS that issue affected other projects too --> https://github.com/actions/setup-python/issues/649

Let me know if one of those ideas helps or not as I'm not really sure what else to suggest.

Dave.

**Comment by DineshSridhar** [comment]
Hi Dave,

Sorry of late reply...

Currently am using python version as 3.10.6

Whether rfswarm can be used to test for mobile automation script by using RF

**Comment by damies13** [comment]
Hi Dinesh,

Did you try another version of python 3.10? As I mentioned the error seems to indicate it's something wrong in threading.py which is a core python component, I don't have an M1 mac to try things on so I'll need your help to resolve this.

> Whether rfswarm can be used to test for mobile automation script by using RF

If robot framework can run the test rfswarm can run it, rfswarm doesn't actually run the test internally it uses the robot framework executable on the agent machine to actually run the test and then listens to the robot framework executable to collect the results.

Another option, if you have another machine to run rfswarm on for now run the manager on the other machine until we can figure out the cause of the error you're getting.

Dave.

**Comment by DineshSridhar** [comment]
Hi Dave,

Thanks for the Reply

I will try to run on another python version..

Meanwhile can u tell me how to configure and run the tescases using RFSwarm..Do u provide steps so I can follow the same to figure out the issue

Do I need to download the ur project or need to clone it..Because I have installed Manager,Agent,report via PIP command..

Did I missed anything..Please share me the steps so it will be easy to figure out.

**Comment by damies13** [comment]
>  have installed Manager,Agent,report via PIP command..

This should be all you need to do, you shouldn't need to download the git project, I have tried this process on several machines on all OS's 

The steps to install are in the documentation:
- [rfswarm_agent](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_agent.md#install-and-setup)
- [rfswarm_manager](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_manager.md#install-and-setup)
- [rfswarm_reporter](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_reporter.md#install-and-setup)

It's basically:
-  Make sure python (and tkinter matching your python version for manager and reporter) is installed
- pip install <rfswarm component> (pip should install all the prerequisites)

I figured you were well passed that stage, the screen shots indicated you had everything installed properly.

The only other thing to remember is on the agent machines you need to make sure you have all the robot framework libraries installed that your tests need.

Dave.

**Comment by damies13** [comment]
Hi @DineshSridhar ,

Did you get a resolution to this issue?

Dave.

**Comment by damies13** [comment]
More than 6 months since a comment, I'll have to assume this is resolved
