### ISSUE TITLE
Issue with Variable Handling on Unix-style OS

### ISSUE THREAD

**Issue by Anker101** [damies13/rfswarm#156]
**Describe the bug**
I encountered an issue while running rfswarm test script on a Unix-style operating system. 
The problem appears to be related to the handling of variables containing the "$" symbol. 

**To Reproduce**
Run the following Robot Framework test script:

*** Variables ***
${endpoint}        my endpoint
${env}             QAENV

*** Test Cases ***
Send GET on API ${endpoint} on ${env}
    Log        ${endpoint}
    Log        ${env}
    Sleep      60

Execute the command: robot -t "Send GET on API ${endpoint} on ${env}" Anker01_variables.robot

Expected Behavior:
The test case should be executed successfully without any errors.

Actual Behavior:
Running the test case on a Unix-style OS results in the following error message:

[ ERROR ] Suite 'Anker01 variables' contains no tests matching name 'Send GET on API  on '.
Try --help for usage information.

**Comment by damies13** [comment]
Confirmed the same issue on MacOS but not on Windows.

I think what's happening is the Unix style OS's are trying to evaluate robot variables ${endpoint} and ${env} as OS environment variables.

Notes to future self:
In the agent's `runthread` function between `test = self.jobs[jobid]['Test']` and `cmd.append('"' + test + '"')` we need to check if the OS is not windows, then check if the test variable contains`${` and replace it with `\${`, that should fix this issue.

**Comment by damies13** [comment]
Confirming test case `Send GET on API ${endpoint} on ${env}` runs

```
RFSwarmAgent: runthread(783): [6:6]	 runthread: test: Send GET on API ${endpoint} on ${env}
RFSwarmAgent: runthread(786): [6:6]	 runthread: test: Send GET on API \${endpoint} on \${env}
RFSwarmAgent: runthread(799): [6:6]	 runthread: localfile: /tmp/rfswarmagent/scripts/Anker01_variables.robot
RFSwarmAgent: runthread(802): [6:6]	 runthread: file: Anker01_variables.robot
RFSwarmAgent: runthread(805): [6:6]	 runthread: farr: ('Anker01_variables', '.robot')
RFSwarmAgent: runthread(828): [6:6]	 runthread: odir: /tmp/rfswarmagent/logs/20230719_211818_Scenario/Anker01_variables_1_1_1689765504_1_1689765513
RFSwarmAgent: runthread(836): [6:6]	 runthread: oprefix: Send_GET_on_API____endpoint__on____env
RFSwarmAgent: runthread(838): [6:6]	 runthread: logFileName: /tmp/rfswarmagent/logs/20230719_211818_Scenario/Anker01_variables_1_1_1689765504_1_1689765513/Send_GET_on_API____endpoint__on____env.log
RFSwarmAgent: runthread(841): [6:6]	 runthread: outputFile: /tmp/rfswarmagent/logs/20230719_211818_Scenario/Anker01_variables_1_1_1689765504_1_1689765513/Send_GET_on_API____endpoint__on____env_output.xml
RFSwarmAgent: runthread(888): [6:6]	 runthread: robotexe: /home/dave/.local/bin/robot
RFSwarmAgent: runthread(896): [6:3]	 Robot run with command: ' robot -t "Send GET on API \${endpoint} on \${env}" -d "/tmp/rfswarmagent/logs/20230719_211818_Scenario/Anker01_variables_1_1_1689765504_1_1689765513" -M RFS_AGENTNAME:hp-elite-desk-800-g3 -v RFS_AGENTNAME:hp-elite-desk-800-g3 -M RFS_AGENTVERSION:1.1.4 -v RFS_AGENTVERSION:1.1.4 -M RFS_DEBUGLEVEL:6 -v RFS_DEBUGLEVEL:6 -M RFS_INDEX:1 -v RFS_INDEX:1 -M RFS_ROBOT:1 -v RFS_ROBOT:1 -M RFS_ITERATION:1 -v RFS_ITERATION:1 -M RFS_SWARMMANAGER:http://localhost:8138/ -v RFS_SWARMMANAGER:http://localhost:8138/ -M RFS_EXCLUDELIBRARIES:BuiltIn,String,OperatingSystem,perftest -v RFS_EXCLUDELIBRARIES:BuiltIn,String,OperatingSystem,perftest --listener "/tmp/rfswarmagent/scripts/RFSListener2.py" -o "/tmp/rfswarmagent/logs/20230719_211818_Scenario/Anker01_variables_1_1_1689765504_1_1689765513/Send_GET_on_API____endpoint__on____env_output.xml" "/tmp/rfswarmagent/scripts/Anker01_variables.robot" '

```

![image](https://github.com/damies13/rfswarm/assets/15232871/f9674e30-41f6-4a51-8a37-f2a53c51b607)

**Comment by damies13** [comment]
![image](https://github.com/damies13/rfswarm/assets/15232871/343de2de-80d4-4d67-8205-8d2f361afd25)
