### ISSUE TITLE
The manager is not able to handle non-existent robot files.

### ISSUE THREAD

**Issue by ArekKuczynski** [damies13/rfswarm#241]
**Describe the bug**
When you have a scenario file with some robot files, but the Manager cannot find them, the Manager will crash.

**To Reproduce**
1. Open Manager
2. Save a scenario file with example robot file.
3. Close Manager
4. Delete or move the robot file
5. Open Manager
6. See error

**Expected behavior**
Manager should handle this with a special message that rejects the scenario file and tells which files are not there. For now, if you want to repair Manager you need to delete the RFSwarmManager.ini and reopen the Manager.

**Screenshots**
![image](https://github.com/damies13/rfswarm/assets/141224434/33217ce7-b9c1-4c77-8e33-ebec93c2db92)
![image](https://github.com/damies13/rfswarm/assets/141224434/25b7cb3e-0ae4-4276-affb-fa48b603a7a7)
![image](https://github.com/damies13/rfswarm/assets/141224434/ab914961-9ebb-410f-976f-28173863417f)

**Additional context**
test.rfs file:
```
[Scenario]
uploadmode = err
scriptcount = 1
graphlist = 

[1]
robots = 10
delay = 10
rampup = 10
run = 10
test = Example Test Case
script = i_dont_exist.robot
```

**Comment by damies13** [comment]
I agree this is a bug :+1:

**Comment by damies13** [comment]
Merged changes fixed this issue
