### ISSUE TITLE
Saving a Reporter template file in Windows does not work correctly

### ISSUE THREAD

**Issue by ArekKuczynski** [damies13/rfswarm#257]
**Describe the bug**
When you save a template file in windows only typing the name you want without .template extension, it will only be saved as a regular file without extension.

**To Reproduce**
1. Open RFSwarm-Reporter
2. Save template
3. Save it by specifying the file name without .template extension
4. See that the file is saved as a regular file

**Expected behavior**
File should be saved with extension even when you only type just a file name
**Screenshots**
![image](https://github.com/damies13/rfswarm/assets/141224434/6e4d1fe1-734c-489f-84c2-b4ba14910013)

then:

![Screenshot 2024-06-27 124729](https://github.com/damies13/rfswarm/assets/141224434/1799b9fd-0e8a-4c71-9374-2419e3b8e50b)

**Desktop (please complete the following information):**
- OS: Windows
- Version: Reporter - 1.3.1

**Comment by damies13** [comment]
Did a little investigating....

In the manager when I save the scenario with [mnu_file_SaveAs](https://github.com/damies13/rfswarm/blob/6f5349ba3a1a61cce726ecb5763387ab4017ea16/rfswarm_manager/rfswarm.py#L7694) I do a check for the file extension and add `.rfs` if it's not there

In reporter when I save the template with [mnu_template_SaveAs](https://github.com/damies13/rfswarm/blob/6f5349ba3a1a61cce726ecb5763387ab4017ea16/rfswarm_reporter/rfswarm_reporter.py#L9714) I don't check the extension and add it if it's missing

Looking at the documentation for [tkinter.filedialog](https://docs.python.org/3/library/dialog.html#module-tkinter.filedialog), there's a `defaultextension` option, so I might try using that first.

Strange that the behavior is different on windows vs MacOS and Linux.

**Comment by damies13** [comment]
Thanks @ArekKuczynski for the test cases and bug fix :+1: Merged into branch v1.3.2
