### ISSUE TITLE
When the Agent is stopped. The Agent is not removed from the Manager while the test is running and the number of robots does not deprecate to 0.

### ISSUE THREAD

**Issue by ArekKuczynski** [damies13/rfswarm#269]
**Describe the bug**
When an Agent is disconnected from the Manager during running test, the Manager will not remove it from the Agents tab and the robot count will not go to 0. So, the test run will probably run forever.
I think it will also not disconnect without the test running.

**To Reproduce**
1. Open Manager
2. Open Agent
3. Agent should be connected to the Manager
4. Run simple test
5. After a while stop Agent
6. Robot count will remain the same and Agent will still marked as active.

**Expected behavior**
When stopping Agent that was connected to the Manager it should be marked as "Offline?" after about 30 seconds and then gets removed from the list after 5 min and when it's removed from the list the robot count should back to zero.

Or maybe a special message that will show after removing Agent from Manager telling us that the agent has been disconnected from the Manager while running test run (only while running test) or even some dialog prompt?

**Screenshots**
Screenshots taken after stopping Agent and waited about 10 minutes:
![image](https://github.com/user-attachments/assets/51b047e6-4f6b-4197-a80d-118ed623eb66)
![image](https://github.com/user-attachments/assets/6dedf9f9-0012-484d-85ba-cad879d88782)

**Desktop (please complete the following information):**
- OS: Windows
- Version v1.4.0 Manager and Agent

**Additional context**
Will create test case for that related to the Issue #203

**Comment by damies13** [comment]
Merged into Release Branch v1.4.0
