### ISSUE TITLE
Console outputs from Manager/Agent/Reporter cannot be saved to the file/variable/etc.

### ISSUE THREAD

**Issue by ArekKuczynski** [damies13/rfswarm#288]
**Describe the bug**
_I will be explaining the error by referring only to the manager but it probably also refers to the agent and reporter._
When running rfswarm -v with for example [Run](https://robotframework.org/robotframework/latest/libraries/OperatingSystem.html#Run) keyword, console output will be saved (-v argument exit rfswarm Manager with `sys.exit(0)`). But running it normally and then closing it, the console output will not be saved this time to the variable or an output file depends on how you start the process and control the stdout output.

When running rfswarm normally there are still some threads running at the end and rfswarm Manager need to be stopped with `os._exit(0)` (**immediate program termination**) because of it.

**To Reproduce**
1. Start rfswarm with [Run](https://robotframework.org/robotframework/latest/libraries/OperatingSystem.html#Run) or [Start Process](https://robotframework.org/robotframework/latest/libraries/Process.html#Start%20Process). The perfect example is Open Manager GUI keyword from Tests/Regression/Manager/GUI_Common.robot.
2. End this process.
3. See that result variable/output file is empty.

**Expected behavior**
Running rfswarm no matter with any arguments or without them should always have console output saved. You can see that the manager writes something to the console but the Bug is that they are not saved except when running it with the arguments -h or -v. 

I think to fix it we need to close Manager/Agent/Reporter only with `sys.exit(0)` because version and help arguments actually close with that function. But to make it possible we need to have only Main thread running and probably change a closing sequence a bit:
```
try:
	sys.exit(0)
except SystemExit:
	try:
		os._exit(0)
	except Exception:
		pass
```
but don't know how yet. I know only that if there are no any extra threads running and we replace all this sequence just with `sys.exit(0)` the console outputs will be saved this time. But at the end we still need to handle some unexpected errors so `os._exit(0)` should be there but maybe in other conditions.

**Screenshots**
After some changes to the Manager manage to get this:
Test:
```
Get Result From Active Process
	${result}= 	Run 	rfswarm
	Log to console 	${\n}${result}
```
Result:
![image](https://github.com/user-attachments/assets/1b2d0cc0-561f-4534-80c3-beb3c9c634a6)
After printing all running threads, we can see that there is only MainThread running so we could exit Manager with `sys.exit(0)` instead  of `os._exit(0)`.

**Desktop (please complete the following information):**
- OS: Windows
- Version 1.4.0

**Comment by damies13** [comment]
Merged into v1.4.0
