### ISSUE TITLE
Reporter time zones are not working properly

### ISSUE THREAD

**Issue by ArekKuczynski** [damies13/rfswarm#308]
**Describe the bug**
When i change the time zone from the original one to something else all graphs are blank and start time and end time are messed up (depends on which time zone you choose). 
After that, when i decided to change it back to the original time zone the graphs are also blank and the start time isn't returning to the original state where it was correct and the graphs contained information's.

It appears that the Reporter does not update the Start Time (startoffset) when the time zone changes.

**To Reproduce**
1. Open Reporter
2. Load some data
3. Create example graph
4. See that graph contain data
5. Change the time zone
6. See that graph is blank this time and Start Time is not correct
7. Return to the original time zone
8. The graph is still empty

**Expected behavior**
Time zones should update Start Time and End Time properly.

**Screenshots**
![image](https://github.com/user-attachments/assets/c8c84a83-ad53-4790-9982-64b223ff7a7b)
![image](https://github.com/user-attachments/assets/eb76b249-69f0-455e-a22a-1084aa954eb1)
Changing time zone:
![image](https://github.com/user-attachments/assets/dd66d2c7-2eca-4fd7-884f-df817076781a)
Notice that Start Time is not correct
![image](https://github.com/user-attachments/assets/81cf5e9c-331d-4c57-9f42-5bebb84275cf)
Back to the original time zone:
![image](https://github.com/user-attachments/assets/608d3700-7937-4f19-b261-311f2a2ea601)
![image](https://github.com/user-attachments/assets/5e0a54e8-233a-4ceb-b8fd-e861a4293fbf)
Repair the times manually:
![image](https://github.com/user-attachments/assets/4a940dd4-fbb2-496d-870a-a870e4523965)
![image](https://github.com/user-attachments/assets/0a9fe06f-5aa9-4209-a0df-1a3b4d0991c9)

**Desktop (please complete the following information):**
- OS: Windows
- Reporter Version: 1.4.0

**Additional context**

**Comment by damies13** [comment]
nice catch :+1:

**Comment by ArekKuczynski** [comment]
The test for this issue will be implemented in the test cases for Issue #36 #37 #38

**Comment by damies13** [comment]
Merged into release branch v1.4.0
