### ISSUE TITLE
<meta charset="utf-8"> missing in the html report file head section.

### ISSUE THREAD

**Issue by ArekKuczynski** [damies13/rfswarm#321]
**Describe the bug**
When trying to generate an html report file with custom header names, for example, in a language other than English, the html file may be saved incorrectly.
This bug was found wile creating Test Cases for Issue #36 <-- Issue #194

**To Reproduce**
1. Open Reporter.
2. Rename the column to include specific characters for the example language. (example in screeshots)
3. Generate HTML report.
4. See wrong translated name in the html file.

**Expected behavior**
HTML should contain <meta charset="utf-8"> in the head section. After that all custom characters should be displayed correctly. 

**Screenshots**
Reporter:
![image](https://github.com/user-attachments/assets/4968201d-9392-4145-9415-1b7e78c30c09)
Robot:
![image](https://github.com/user-attachments/assets/475f67f0-0623-4224-b364-10bfe70a8a56)
HTML file:
![image](https://github.com/user-attachments/assets/9960a1d5-f4b9-451a-a89c-d6286e6a409b)

**Desktop (please complete the following information):**
- OS: Ubuntu
- Version: RFS Reporter 1.4.0

**Comment by damies13** [comment]
Can you confirm I typed these correctly?
- Średnia
- Pomyślnie

**Comment by ArekKuczynski** [comment]
Okay this is actually already resolved in v1.4.0.
Test cases (Passed): https://github.com/NiceProjectPoland/rfswarm/actions/runs/11846602159/job/33014634674
