### ISSUE TITLE
Add support for initialization files

### ISSUE THREAD

**Issue by vaghetti** [damies13/rfswarm#90]
**Is your feature request related to a problem? Please describe.**
rfswarm does not support [Initialization files](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#initialization-files)

**Describe the solution you'd like**
I started using Robot Framework 3 days ago, so take my advice with a grain of salt. 
My initial suggestion would be to check if there's an __init__.* file in the same folder as the test being executed. If there is, this file should also be sent to the agent so that RF picks it up and uses it. It would also be nice to show some graphical indicator that an init file was detected and will be used. 

**Describe alternatives you've considered**
It would also be possible to have an optional field for initialization files in the UI, so that you can select it manually if you have one.

**Comment by damies13** [comment]
Hi Douglas,

> check if there's an init.* file in the same folder as the test being executed

I will implement this functionality under this issue number, I plan to start working on this soon, and hope to include it in the next release.

> It would also be nice to show some graphical indicator that an init file was detected and will be used.

If you run the manager with debug level 3 it will show you the files identified for transferring to the agent, with the file hash, this hash is how the agent uniquely identifies the file and also how rfswarm knows when the file has changed and needs to get the agent to download a new copy of the file.
If you run the agent with debug level 1 it will show you the filename and hash as the file is created locally
As this process is quite reliable and well proven (it was part of the first version of rfswarm) I don't see a need to show this in the gui, if you need to see this information you can run with the higher debug mode, most of the time I expect you wouldn't need this, but happy to hear your thoughts on if this is enough.

> It would also be possible to have an optional field for initialization files in the UI, so that you can select it manually if you have one.

As discussed on Discord there is the option of using ```Metadata 	 File``` for transferring files that aren't automatically identified for transfer, Unless there is a real need to have this option available via the gui I think for now this is the best place for addressing additional files to be transferred as it keeps the files with the test case

**Comment by damies13** [comment]
> check if there's an init.* file in the same folder as the test being executed

This has been implemented and merged into the v0.8.0 branch, so I will close this issue for now, if after reviewing my comments above you still think something extra needs to be added to the gui, we can re-open this issue.

Dave.
