### ISSUE TITLE
Issue with detecting resource files in robot files

### ISSUE THREAD

**Issue by tareked20** [damies13/rfswarm#94]
**Describe the bug**
I think there is a bug in rfswarm where it tries to parse through a robot file to find resource such as files in Metadata tags.
It seems to look for any robot files and grabbing its extension then comparing its extension to (robot, resource)
However the call to get the extension seems to return the dot part of the extension and so the compare fails to identify the robot file and never parses the robot file for referenced files.

Below the log lines show the extension is:  .robot
RFSwarmBase: find_dependancies(1232): [9:9]	 RFSwarmCore: find_dependancies: localdir D:\VSCodeBase\T1-Bitbucket\performance_testing\test_scripts\T1\CORE 	[0.8.0 @2021-07-07 02:37:38]
RFSwarmBase: find_dependancies(1235): [9:9]	 RFSwarmCore: find_dependancies: filename, fileext: D:\VSCodeBase\T1-Bitbucket\performance_testing\test_scripts\T1\CORE\SimpleLoginLogout_Script001 .robot 	[0.8.0 @2021-07-07 02:37:38]

However, looking through the rfswarm.py file I can see that based on the extension returned, the string compare will fail due to the . in the extension 
line 1237		if (fileext.lower() in ['robot', 'resource'] and keep_going):

This can be resolved by having a look for the dot at the beginning and removing the dot
line 1237		if (((fileext.lower()).replace('.', '', 1)) in ['robot', 'resource'] and keep_going):

**To Reproduce**
- Create a robot script with a resource line similar to below in the *** SETTINGS *** section:
 Metadata  FILE  testdata.csv
- Run RFSwarm and RFSwarm agent.
- When the Test is executed the testdata.csv file should be copied across to the agent. It does not.

**Expected behavior**
- The testdata.csv file should be copied across to the agent. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 2019
 - Browser N/A
 - Version (Agent and Manager) [0.8.0]

**Comment by damies13** [comment]
@tareked20 You are correct this is a bug, surprising that no one had come across this before. I will get this resolved soon.

> and ext is empty or begins with a period and contains at most one period
https://docs.python.org/3/library/os.path.html

**Comment by damies13** [comment]
Fix merged into release v0.8.1
